# report_failing_paths.tcl
#
# Use with: quartus_sta -t report_failing_paths.tcl
#
# Dumps the worst N setup paths for each clock domain to
# output_files/MultiComp.failing_paths.rpt, including full
# combinational expansion of each path. Read this report to
# identify which combinational chain is missing its setup window
# and where to insert a pipeline register.

project_open MultiComp -revision MultiComp

create_timing_netlist
read_sdc
update_timing_netlist

set rpt "output_files/MultiComp.failing_paths.rpt"

# Truncate / create the file with a banner.
set fh [open $rpt w]
puts $fh "TimeQuest failing-paths report"
puts $fh "Generated by report_failing_paths.tcl"
puts $fh "============================================================"
close $fh

# 20 worst setup paths overall, with full combinational expansion.
report_timing                                  \
   -setup                                      \
   -npaths 20                                  \
   -detail full_path                           \
   -panel_name {Top 20 setup}                  \
   -file $rpt                                  \
   -append                                     \
   -multi_corner

# 20 worst hold paths overall.
report_timing                                  \
   -hold                                       \
   -npaths 20                                  \
   -detail full_path                           \
   -panel_name {Top 20 hold}                   \
   -file $rpt                                  \
   -append                                     \
   -multi_corner

# Focused: 20 worst setup paths on the system PLL output (clk_sys), the
# clock that's failing. This is where the MMU/SDRAM/blockram logic lives.
report_timing                                  \
   -setup                                      \
   -npaths 20                                  \
   -detail full_path                           \
   -from_clock {emu|pll|pll_inst|altera_pll_i|general[0].gpll~PLL_OUTPUT_COUNTER|divclk} \
   -to_clock   {emu|pll|pll_inst|altera_pll_i|general[0].gpll~PLL_OUTPUT_COUNTER|divclk} \
   -panel_name {Top 20 setup on clk_sys} \
   -file $rpt                                  \
   -append                                     \
   -multi_corner

delete_timing_netlist
project_close
