( case statement )
: CASE  ( -- 0 ) 0 ; IMMEDIATE
: OF    POSTPONE OVER  POSTPONE =  POSTPONE IF  ; IMMEDIATE
: ?OF   ( flag -- ) POSTPONE
              OVER   POSTPONE IF  POSTPONE DROP ; IMMEDIATE
: ENDOF ( -- ) POSTPONE ELSE ; IMMEDIATE
: ENDCASE POSTPONE DROP  
      BEGIN ?DUP  WHILE  POSTPONE THEN  REPEAT ; IMMEDIATE







