( SCREEN EDITOR 1 OF 11 ) HEX 
LIMIT @ 10 + CONSTANT ZZZ ( WORKING BUFFER)
DECIMAL
                              1024 CONSTANT 1K
   64 CONSTANT 64               63 CONSTANT 63
      VARIABLE MODIFIED            VARIABLE ROW
      VARIABLE COL                 VARIABLE I/R
      VARIABLE LOBLK               VARIABLE HIBLK
( STORE LOWEST AND HIGHEST BLOCKS TO EDIT ON YOUR COMPUTER)
0 LOBLK  ! 255 HIBLK !
: ---- ; ( "NO OPERATION" FOR EXECUTION VECTOR)
: CLEAN 0 MODIFIED ! ; : DIRTY 1 MODIFIED ! ; ( BUFFER STATE)



( 16)