\ SCREEN EDITOR 2 OF 11
: PADDR ( N --) CREATE , DOES> @ ZZZ + ;
   1K 2 *      PADDR BLINE ( LAST LINE IN CIRCULAR BUFFER)
   1K 2 * 64 + PADDR LBUFF ( ADDRESS COPY/REPLACE LINE)




( MOVE CURSOR TO ROW,COL. ROW,COL START AT 0,0 TERMINAL AT 1,1)
: <CXY> .ESC[
          ROW @ 2 + 10 / 48 + EMIT ROW @ 2 + 10 MOD 48 + EMIT
 59 EMIT  COL @ 1+  10 / 48 + EMIT COL @ 1+  10 MOD 48 + EMIT
 72 EMIT ;
: <CLR>   .ESC[ 50 EMIT 74 EMIT ; ( CLR SCREEN, CURSOR HOME)
( GET KEY, FORCE TO UPPER-CASE)
: UCKEY ( -- C) KEY DUP 97 123 WITHIN IF 32 XOR THEN ;