\ SCREEN EDITOR 3 OF 11
: CURSOR@ ( -- R C) ROW @ COL @ ; ( RECALL ROW AND COL)
: CURSOR! ( R C --) COL ! ROW ! ; ( STORE  ROW AND COL)
( DEFINE <stl> AND <hmc> HERE IF POSSIBLE AND USE BELOW)
: <SOL>   0 COL !   <CXY> ; ( MOVE CURSOR TO START OF LINE)
: <HOM> 0 0 CURSOR! <CXY> ; ( MOVE CURSOR TO UPPER LEFT)
: BABOVE ( -- N) ROW @ 64 * ; ( #BYTES IN ROWS ABOVE CURSOR)
: BBELOW ( -- N) 16 ROW @ - 64 * 1K + ; ( BYTES BELOW CURSOR)
: OFFSET ( -- N) BABOVE COL @ + ; ( #BYTES CURSOR INTO BUFFER)

: CPOS   ( -- ADDR) ZZZ OFFSET + ; ( CURSOR ADDRESS)
: LSTART ( -- ADDR) ZZZ BABOVE + ; ( START-LINE ADDRESS)
: LEND   ( -- ADDR) LSTART 63 + ;  ( END-LINE ADDRESS)

: BLEFT  ( -- N) LEND CPOS - ; ( BYTES LEFT IN LINE)
