\ SCREEN EDITOR 4 OF 11
( IF POSSIBLE DEFINE <BSP> <ADV> <ULF> AND <DLF> IN           )
( THESE LINES AND USE THEM IN PLACE OF <CXY> BELOW            )

: LEFT  COL @  0 > IF -1 COL +! <CXY> ( OR <BSP>) THEN ;
: RIGHT COL @ 63 < IF  1 COL +! <CXY> ( OR <ADV>) THEN ;
: UP    ROW @  0 > IF -1 ROW +! <CXY> ( OR <ULF>) THEN ;
: DOWN  ROW @ 15 < IF  1 ROW +! <CXY> ( OR <DLF>) THEN ;
: <EEL> ( --) BLEFT 1+ SPACES <CXY> ; ( ERASE TO END OF LINE)
: NEWLINE ( --) <SOL> DOWN ; ( CURSOR, START NEXT LINE)
: SHOWLINES ( --) CURSOR@ 16 ROW @ ( DISPLAY LINES)
  DO I ROW ! <SOL> LSTART 64 TYPE  ( TODO OPTIMISE! )
  LOOP CURSOR! <CXY> ;
: SHOWBLK ( --) CURSOR@ <HOM> SHOWLINES CURSOR! <CXY> ;
: TYPELINE ( --) CPOS BLEFT 1+ TYPE <CXY> ;
