\ SCREEN EDITOR 5 OF 11
: MODE ( --) I/R @ 0= I/R ! STAT ; ( SELECT INSERT/REPLACE)
: CLEAN MODIFIED @ 0 <> IF 0 MODIFIED ! STAT THEN ;
: DIRTY MODIFIED @ 0=   IF 1 MODIFIED ! STAT THEN ;
: BCLEAR ( --)       ZZZ 1K + 1152 BL FILL ;   ( CLEAR BUFFER)
: SCLEAR ( --) DIRTY ZZZ 1K BL FILL SHOWBLK ;  ( CLEAR SCREEN)
: LOADBLK ( --) SCR @ BLOCK ZZZ 1K CMOVE ;     ( LOAD BLOCK)
: RESTORE ( --) CLEAN LOADBLK SHOWBLK STAT ;   ( RE-LOAD BLOCK)

: UPDATES ( --) CLEAN STAT                     ( UPDATE BLOCK)
  ZZZ SCR @ BLOCK 1K CMOVE UPDATE ;




