\ SCREEN EDITOR 7 OF 11
: OPENUP ( --)   ( OPEN TEXT AT CURSOR POSITION IN BUFFER)
  DIRTY COL @ 64 < IF
    CPOS DUP 1+ BLEFT CMOVE> BL CPOS C! THEN ;
: OPEN ( --) OPENUP TYPELINE ; ( OPEN TEXT AT CURSOR)

: TRUNC ( --) DIRTY <EEL> CPOS BLEFT BL FILL ; ( TRUNCATE LINE)

: OVERTYPE ( CHAR --) COL @ 64 <   ( REPLACE CHAR AT CURSOR)
  IF DUP EMIT CPOS C! 1 COL +! ELSE DROP THEN ;

: INSERT ( CHAR --) OPENUP OVERTYPE TYPELINE ; ( INSERT CHAR)
: DELETE ( --) DIRTY COL @ 64 <                ( DELETE CHAR)
  IF CPOS 1+ CPOS BLEFT CMOVE
     BL LEND C! <EEL> TYPELINE
  THEN ;