\ SCREEN EDITOR 8 OF 11
: CLINE ( --) LSTART LBUFF  64 CMOVE ; ( COPY LINE TO BUFFER)

: PLINE ( --) LBUFF LSTART  64 CMOVE ( PUT LINE FROM BUFFER)
  CURSOR@ <SOL> TYPELINE CURSOR! <CXY> DIRTY ;

: KLINE ( --)                 ( KILL LINE INTO CIRCULAR BUFFER)
  DIRTY LSTART BLINE 64 CMOVE              ( MOVE CURRENT LINE)
  LSTART 64 + LSTART BBELOW CMOVE             ( MOVE BUFFER UP)
  SHOWLINES ;                          ( DISPLAY CHANGED LINES)

: ILINE                     ( INSERT LINE FROM CIRCULAR BUFFER)
  DIRTY LSTART DUP 64 + BBELOW CMOVE>            ( MOVE BUFFER)
  BLINE LSTART 64 CMOVE         ( MOVE LINE FROM BOTTOM BUFFER)
  SHOWLINES ;                          ( DISPLAY CHANGED LINES)
