\ SCREEN EDITOR 10 OF 11
: EDITCASE ( F CHAR -- F')
  DUP 1 27 WITHIN             ( A PERMISSIBLE CONTROL CHAR? ..)
  IF KEYDO                           ( IF SO, EXECUTE COMMAND)
  ELSE DUP 32 127 WITHIN             ( IF NOT, PRINTABLE CHAR?)
    IF I/R @ DIRTY                   ( IF SO,  SEE WHAT MODE..)
      IF INSERT ELSE OVERTYPE THEN     ( AND INSERT OR REPLACE)
    ELSE DROP           ( BUT DISCARD IF CHAR IS NOT PRINTABLE)
    THEN
  THEN ;

: EDINIT ( BLK --) SCR ! RESTORE ;
: EDITLOOP ( --) EDINIT 0 BEGIN KEY EDITCASE DUP UNTIL DROP ;

: EDIT ( BLK --) <HOM> <CLR> EDITLOOP <HOM> <CLR> ;
